############################# English ############################
[en]
languageName = "En"
title = "Sparklee | Favourite Places ❤️"
contentDir = "content/english" # content/english
weight = 1
########### footer content ##########
footer_menu_left = "Contact"
footer_menu_middle = "Legal"
#footer_menu_right = "Support"
footer_content = "The app to share your favorite places ❤️✨"
# copyright
copyright = "Copyright © 2021 Sparklee. All rights reserved."
# Design By [Themefisher](https://themefisher.com/) Develop By [Gethugothemes](https://gethugothemes.com/)



############################# French ############################
[fr]
languageName = "Fr"
title = "Sparklee | Adresses Coup de coeur ❤️"
contentDir = "content/french" 
weight = 2
########### footer content ##########
footer_menu_left = "Contact"
footer_menu_middle = "Légal"
#footer_menu_right = "Support"
footer_content = "L'appli pour partager tes adresses coup de coeur ❤️✨"
# copyright
copyright = "Copyright © 2021 Sparklee. Tous droits réservés."