#### MAIN MENU ####

[[main]]
name = "Home"
url = "/"
weight = 1

#[[main]]
#name = "Blog"
#url = "blog"
#weight = 2

#[[main]]
#name = "Pricing"
#url = "pricing"
#weight = 3

[[main]]
name = "Fonctionnalités"
url = "#app-aims"
weight = 3

[[main]]
name = "Contact"
url = "contact"
weight = 4


#### FOOTER ####

#### LEFT ####

# footer menu left
[[footer_left]]
name = "Contacte-nous!"
url = "contact"

[[footer_left]]
name = "✉️ sparklee@mailo.com"
#url = "mailto:sparklee@mailo.com"


#### MIDDLE ####

# footer menu middle
#[[footer_middle]]
#name = "Pricing"
#url = "pricing"

[[footer_middle]]
name = "Mentions légales"
url = "#"
#url = "privacy-policy"

[[footer_middle]]
name = "CGU"
url = "#"
#url = "terms-conditions"


#### RIGHT ####

#deleted

