#################### default parameters ################################
logo = "images/logo_sparklee.png"
logo_width = "200px"
# Meta data
description = "App to Share your favorite places"
author = "Sparklee"
# contact form action
contact_form_action = "https://formspree.io/f/mleabjny" # contact form works with https://formspree.io

# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation buttons
[navigation_button]
enable = true
label = "Notify Me"
link = "" 
#link defined directly in header.html ! TO DEFINE HERE?

  
############################# social site ########################
#[[social]]
#title = "facebook"
#icon = "fab fa-facebook" # themify icon : https://themify.me/themify-icons
#link = "#"

#[[social]]
#title = "twitter"
#icon = "fab fa-twitter" # themify icon : https://themify.me/themify-icons
#link = "#"

[[social]]
title = "instagram"
icon = "fab fa-instagram" # themify icon : https://themify.me/themify-icons
link = "https://www.instagram.com/sparklee.app/"

[[social]]
title = "linkedin"
icon = "fab fa-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://www.linkedin.com/company/sparklee/"